
import React, { useState, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { MapPin, Calendar, DollarSign, Plane, Sparkles, Globe, ArrowRight } from 'lucide-react';
// import { storageService } from '../services/storage';
import { tripService } from '../services/tripService'; // Import API service
import AuthContext from '../context/AuthContext';

const CreateTrip = () => {
  const { user } = useContext(AuthContext);
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    title: '',
    destination: '',
    startDate: '',
    endDate: '',
    travelers: {
      adults: 1,
      children: 0
    },
    totalBudget: 1000
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const start = new Date(formData.startDate);
      const end = new Date(formData.endDate);
      const diffTime = Math.abs(end.getTime() - start.getTime());
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)) + 1;

      // Create the trip object structure expected by frontend components
      const newTripData = {
        // id will be generated by backend
        userId: user?.id,
        title: formData.title,
        destination: formData.destination,
        startDate: formData.startDate,
        endDate: formData.endDate,
        budget: {
          total: formData.totalBudget,
          spent: 0
        },
        travelers: formData.travelers,
        itinerary: Array.from({ length: diffDays }).map((_, i) => ({
          dayNumber: i + 1,
          activities: []
        }))
      };

      // Call API
      const createdTrip = await tripService.createTrip(newTripData);

      // Navigate to the new ID from backend
      navigate(`/trip/${createdTrip.id}`);
    } catch (error) {
      console.error("Failed to create trip:", error);
      alert("Failed to create trip. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  // Animation variants
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { duration: 0.6, staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1, transition: { duration: 0.4 } }
  };

  return (
    <div className="min-h-screen flex w-full bg-[#0a0a0f] overscroll-none">

      {/* Left Side - Visuals & Tips */}
      <div className="hidden lg:flex w-5/12 relative overflow-hidden text-white bg-gray-950">
        <div className="absolute inset-0">
          <img
            src="https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=1935&auto=format&fit=crop"
            alt="Travel Planning"
            className="w-full h-full object-cover opacity-40 mix-blend-overlay"
          />
          <div className="absolute inset-0 bg-gradient-to-br from-blue-900/80 to-gray-950/90" />
        </div>

        <div className="relative z-10 p-12 flex flex-col justify-between h-full w-full">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-teal-500/100/20 border border-blue-400/30 text-blue-200 text-sm font-medium mb-6">
              <Sparkles className="w-4 h-4" />
              <span>AI-Powered Planner</span>
            </div>
            <h2 className="text-4xl font-bold mb-4 leading-tight">
              Plan your perfect <br />
              <span className="text-blue-400">getaway.</span>
            </h2>
            <p className="text-gray-400 text-lg">
              Create a detailed itinerary, manage your budget, and discover new experiences.
            </p>
          </div>

          {/* Quick Tips Card */}
          <div className="bg-white/10 backdrop-blur-md border border-white/10 p-6 rounded-2xl">
            <h3 className="font-bold flex items-center gap-2 mb-3">
              <Globe className="w-5 h-5 text-blue-400" />
              Pro Travel Tip
            </h3>
            <p className="text-sm text-gray-400 leading-relaxed">
              "Be flexible with your dates. Sometimes shifting your trip by just one day can save you significant money on flights and accommodation."
            </p>
          </div>
        </div>
      </div>

      {/* Right Side - Form */}
      <div className="w-full lg:w-7/12 flex items-center justify-center p-6 lg:p-12 relative">
        <div className="max-w-2xl w-full">
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
          >
            <div className="mb-10">
              <h1 className="text-3xl lg:text-4xl font-bold text-white mb-3">Create New Trip</h1>
              <p className="text-gray-500 text-lg">Enter details to generate your comprehensive travel plan.</p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-8">

              {/* Trip Title & Destination */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <motion.div variants={itemVariants}>
                  <label className="block text-sm font-bold text-gray-300 mb-2 ml-1">Trip Name</label>
                  <div className="relative group">
                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                      <Plane className="h-5 w-5 text-gray-600 group-focus-within:text-teal-400 transition-colors" />
                    </div>
                    <input
                      type="text"
                      required
                      placeholder="e.g. Summer in Italy"
                      className="w-full pl-12 pr-4 py-4 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500/50 transition-all shadow-none group-hover:bg-[#0a0a0f]"
                      value={formData.title}
                      onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    />
                  </div>
                </motion.div>

                <motion.div variants={itemVariants}>
                  <label className="block text-sm font-bold text-gray-300 mb-2 ml-1">Destination</label>
                  <div className="relative group">
                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                      <MapPin className="h-5 w-5 text-gray-600 group-focus-within:text-teal-400 transition-colors" />
                    </div>
                    <input
                      type="text"
                      required
                      placeholder="e.g. Rome, Italy"
                      className="w-full pl-12 pr-4 py-4 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500/50 transition-all shadow-none group-hover:bg-[#0a0a0f]"
                      value={formData.destination}
                      onChange={(e) => setFormData({ ...formData, destination: e.target.value })}
                    />
                  </div>
                </motion.div>
              </div>

              {/* Dates */}
              <motion.div variants={itemVariants} className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-bold text-gray-300 mb-2 ml-1">Start Date</label>
                  <div className="relative group">
                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                      <Calendar className="h-5 w-5 text-gray-600 group-focus-within:text-teal-400 transition-colors" />
                    </div>
                    <input
                      type="date"
                      required
                      className="w-full pl-12 pr-4 py-4 rounded-xl bg-white/5 border border-white/10 text-white focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500/50 transition-all shadow-none group-hover:bg-[#0a0a0f] [color-scheme:light]"
                      value={formData.startDate}
                      onChange={(e) => setFormData({ ...formData, startDate: e.target.value })}
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-bold text-gray-300 mb-2 ml-1">End Date</label>
                  <div className="relative group">
                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                      <Calendar className="h-5 w-5 text-gray-600 group-focus-within:text-teal-400 transition-colors" />
                    </div>
                    <input
                      type="date"
                      required
                      className="w-full pl-12 pr-4 py-4 rounded-xl bg-white/5 border border-white/10 text-white focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500/50 transition-all shadow-none group-hover:bg-[#0a0a0f] [color-scheme:light]"
                      value={formData.endDate}
                      onChange={(e) => setFormData({ ...formData, endDate: e.target.value })}
                    />
                  </div>
                </div>
              </motion.div>

              {/* Travelers */}
              <motion.div variants={itemVariants} className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-bold text-gray-300 mb-2 ml-1">Adults</label>
                  <input
                    type="number"
                    min="1"
                    required
                    className="w-full px-4 py-4 rounded-xl bg-white/5 border border-white/10 text-white focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500/50 transition-all shadow-none group-hover:bg-[#0a0a0f]"
                    value={formData.travelers?.adults || 1}
                    onChange={(e) => setFormData({
                      ...formData,
                      travelers: { ...formData.travelers, adults: parseInt(e.target.value) || 1 }
                    })}
                  />
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-300 mb-2 ml-1">Children</label>
                  <input
                    type="number"
                    min="0"
                    className="w-full px-4 py-4 rounded-xl bg-white/5 border border-white/10 text-white focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500/50 transition-all shadow-none group-hover:bg-[#0a0a0f]"
                    value={formData.travelers?.children || 0}
                    onChange={(e) => setFormData({
                      ...formData,
                      travelers: { ...formData.travelers, children: parseInt(e.target.value) || 0 }
                    })}
                  />
                </div>
              </motion.div>

              {/* Budget */}
              <motion.div variants={itemVariants}>
                <label className="block text-sm font-bold text-gray-300 mb-2 ml-1">Total Budget</label>
                <div className="relative group max-w-sm">
                  <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                    <DollarSign className="h-5 w-5 text-gray-600 group-focus-within:text-green-500 transition-colors" />
                  </div>
                  <input
                    type="number"
                    required
                    min="1"
                    placeholder="5000"
                    className="w-full pl-12 pr-4 py-4 rounded-xl bg-white/5 border border-white/10 text-white placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-green-500/20 focus:border-green-500 transition-all shadow-none group-hover:bg-[#0a0a0f]"
                    value={formData.totalBudget}
                    onChange={(e) => setFormData({ ...formData, totalBudget: parseInt(e.target.value) || 0 })}
                  />
                  <div className="absolute inset-y-0 right-0 pr-4 flex items-center pointer-events-none">
                    <span className="text-gray-600 font-medium">USD</span>
                  </div>
                </div>
                <p className="text-xs text-gray-600 mt-2 ml-1">Estimated budget for the entire trip excluding flights.</p>
              </motion.div>

              <motion.div variants={itemVariants} className="pt-4">
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="w-full bg-teal-500 text-black py-4 rounded-xl font-bold text-lg hover:bg-teal-400 transition-all shadow-lg shadow-teal-500/20 flex items-center justify-center gap-2 transform active:scale-[0.99] disabled:opacity-70 disabled:cursor-not-allowed"
                >
                  {isSubmitting ? (
                    <>Creating Trip... <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /></>
                  ) : (
                    <>Start Planning <ArrowRight className="w-5 h-5" /></>
                  )}
                </button>
              </motion.div>

            </form>
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default CreateTrip;


